# Generated by Django 4.1.6 on 2023-03-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Pet Food', 'Pet Food'), ('Snack', 'Snack')], default='Chocolate', max_length=100, verbose_name='Category'),
        ),
    ]
